# This file was generated by setup.py...

gcVERSION_STRING = "0.1.72.1"
gcVERSION_NUMBER = "0.1.72"
gcMAJOR_VERSION = 0
gcMINOR_VERSION = 1
gcBUILD_NUMBER = 72
gcSTATUS = "1"
gcDB_STRUCT = 0.1
gcDB_DATA = 0.1
